name: MLOps CI Pipeline

on:  
  push:  # Runs on every push to the repo
    branches:
      - main  # Adjust if using a different branch
  pull_request:  # Runs on PRs to main branch
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"  # Adjust to your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
          pip install pytest
          pip install -r <(grep -v 'pywin32' requirements.txt)

      - name: Run Pytest Tests
        run: |
          pytest tests/
